### ISSUE TITLE
VIIRS SDR reflectance has non physical values at low sun elevation angles at slopes facing the sun

### ISSUE THREAD

**Issue by TAlonglong** [pytroll/satpy#1090]
VIIRS SDR reflectance has non physical values at low sun elevation angles at slopes facing towards the sun. See attached image.
The problem is due to the way the reflectance is calculated in CSPP.

![diana_viirs-holes](https://user-images.githubusercontent.com/19924146/75452171-16b00680-5972-11ea-88cb-fd739e061a75.png)

A possible solution is to make the reflectance calculations from radiances.

**Comment by djhoese** [comment]
Is this all bands? Only specific ones? Isn't this a known issue for one of the VIIRS bands (overflow on the detector level)?

**Comment by TAlonglong** [comment]
Hm yes. I think you are right @djhoese. Its the M07 channel which is regenerated from one of the I channels (I2) I think.

And some issue there. I think we discussed this some time ago(some years) But I had forgot about it.

Hm, maybe I can use the I2 channel instead of the M07 channel?

**Comment by TAlonglong** [comment]
![diana_viirs-holes](https://user-images.githubusercontent.com/19924146/75486340-a377b600-59ac-11ea-8e91-9dbe876e7a8b.gif)

Of course the problem for reflectance is in the I02 channel also, but the problem is smaller. One pixel in I02 will give 4 pixels I guess in M07

**Comment by mraspaud** [comment]
@TAlonglong I've seen such hole in some bands for Modis too, and to generate composites using those bands, we use a `Filler` compositor as a workaroud:
https://github.com/pytroll/satpy/blob/master/satpy/etc/composites/modis.yaml#L59-L71
```yaml
  overview:
    compositor: !!python/name:satpy.composites.GenericCompositor
    prerequisites:
    - name: '1'
      modifiers: [sunz_corrected]
    - compositor: !!python/name:satpy.composites.Filler
      prerequisites:
      - name: '2'
        modifiers: [sunz_corrected]
      - name: '1'
        modifiers: [sunz_corrected]
    - name: '31'
    standard_name: overview
```
Basically, it fills the missing parts of the channel with values from another channel...
Maybe this can work here too ?
