### ISSUE TITLE
Satpy doesnt't skip resampling if source and target areas match exactly

### ISSUE THREAD

**Issue by peters77** [pytroll/satpy#1102]
If I resample a static image with a given projection like `euro1` to the same projection Satpy should skip the resampling. At the moment resampling seems to take place. 

**To Reproduce**

Code:

```
area = 'euro1'
new_scene = global_scene.resample(area, radius_of_influence = 20000, cache_dir='/tmp')

```
Composite:

```
  static_day_euro1:
    compositor: !!python/name:satpy.composites.StaticImageCompositor
    standard_name: static_night
    filename: /home/cpeters/satpy/backgrounds/euro1_day.png
    area: euro1
```

As provided by @pnuu , some check like 

` if self.source_geo_def == self.target_geo_def`

should take place.
