### ISSUE TITLE
Reading "sst_dtime" band using "slstr_l2" reader

### ISSUE THREAD

**Issue by dtlloyd** [pytroll/satpy#1159]
Hi,

I realise the "slstr_l2" reader is still in beta. Nevertheless it works really well for me for reading Sentinel 3 level 2 SST data including the quality file. I would also like to read in another band contained in the dataset called "sst_dtime". The reader file "slstr_l2.yaml" doesn't contain this possibility yet so I decided to add:
```
  sst_dtime:
    name: sst_dtime
    sensor: slstr_l2
    coordinates: [longitude, latitude]
    file_type: SLSTRB
    resolution: 1000
    view: nadir
    units: seconds
    standard_name: sst_dtime

```
to "slstr_l2.yaml", just copying the syntax used for the bands that already work using this reader. This "naive" attempt throws up the following error when I try to reproject the "sst_dtime" band using the resample function:
```
Invalid integer data type 'm'.
```

I appreciate that I am trying to do something that it not currently supported by Satpy, but if you could offer me any hints or suspicions about what might be causing this error I am happy to try to fix this on my own.

Thanks,
David
