### ISSUE TITLE
DayNightCompositor doesn't survive missing day or night part

### ISSUE THREAD

**Issue by mraspaud** [pytroll/satpy#1329]
**Describe the bug**
The DayNightCompositor doesn't work if one of the required parts is missing. However, during daytime for example, only the day composite is needed.

**To Reproduce**

```python
# With a daytime Metop AVHRR data scene:
scene.load(['overview_with_cloudtop'])

```

**Expected behavior**
I would expect the composite to check whether the each day/night part is actually needed before failing.

**Actual results**
The composite isn't loaded.

**Comment by pnuu** [comment]
I have this composite in use with Satpy version 0.19.1 and have not had crashes. So something in the recent refactorings have changed how things are handled in the composite loading?

**Comment by pnuu** [comment]
And for completenes my composite configs:

```yaml
  overview_with_cloudtop:
    compositor: !!python/name:satpy.composites.DayNightCompositor
    standard_name: overview_with_cloudtop
    lim_low: 87.0
    lim_high: 88.0
    prerequisites:
      - overview
      - cloudtop

  overview:
    compositor: !!python/name:satpy.composites.GenericCompositor
    prerequisites:
    - name: '1'
      modifiers: [sunz_corrected]
    - name: '2'
      modifiers: [sunz_corrected]
    - name: '4'
    standard_name: overview

  cloudtop:
    compositor: !!python/name:satpy.composites.GenericCompositor
    prerequisites:
    - name: '3b'
    - name: '4'
    - name: '5'
    standard_name: cloudtop
```
