### ISSUE TITLE
Specifying wavelength/frequency in other ways than just min, nominal and max

### ISSUE THREAD

**Issue by adybbroe** [pytroll/satpy#1369]
## Feature Request

**Is your feature request related to a problem? Please describe.**

The spectral wavelength range specified in the reader config file assumes it is  given as [min, nominal, max] as far as I can see. Like for AVHRR channel 1:
`wavelength: [0.58, 0.63, 0.68]`

However, for PMW sounders for instance it is quite often the case that the channels are placed as bands on each side of an absorption line, as for instance for MHS on Metop. MHS channels 3, 4 and 5 for instance are given by a central frequency of 183.31 and with bands on each side of this central one, like ch3=183.31 +- 1.0 GHz, and bandwidth is 1.0 GHz. How would you specify this? For instance it could be `[183.31, -1., 1., 1.0]`, but that would be incompatible with the current standard!
Also polarisation is critical in identifying the type of band. How is that done? 
And finally, it is custom to use the frequency rather than the wavelength when considering MW channels, as above!

**Describe the solution you'd like**

A suggestion (haven't given it much thought yet though):
```
        band_specification:
          frequency: True
          unit: GHz
          central: 183.31
          left: -1.0
          right: 1.0
          bandwidth: 1.0
```

**Describe any changes to existing user workflow**
Are there any backwards compatibility concerns? Changes to the build process? Additional dependencies?

**Additional context**
Have you considered any alternative solutions or is there anything else that would help describe your request.

**Comment by mraspaud** [comment]
Thanks for raising this issue. I had to think about it a bit, but I think there are sufficient mechanisms in satpy/master now to address it. Probably these mechanisms are not documented enough, hence the questions.

The new DataID introduced in #1088 have made possible to customise how to identify bands for each sensor individually.

Here is an example with added polarisation: https://github.com/pytroll/satpy/blob/master/satpy/etc/readers/sar-c_safe.yaml#L7-L22

So you could add such a parameter for the MHS sensor in the reader configuration.

Secondly, as you can see in the example above, nothing says that you need to have a wavelength parameter. In principle, you can define your own frequency class and use it in the band identification.
Here is the definition of the WavelengthRange class:
https://github.com/pytroll/satpy/blob/7f11a0ef150efbdb94aec630296ea9803b30fa45/satpy/dataset/dataid.py#L83-L163

So you could define a `FrequencyStrip` class, that fulfills the requirements described here: https://satpy.readthedocs.io/en/latest/dev_guide/satpy_internals.html#types
For example, it could accept a (yaml) dict of parameters like you give as example, and then you add it in the band identification keys like described here:
https://satpy.readthedocs.io/en/latest/dev_guide/satpy_internals.html#types
as eg:
```yaml
data_identification_keys:
  name:
    required: true
  frequency:
    type: !!python/name:satpy.readers.my_mhs_reader.FrequencyStrip
  resolution:
  polarization:
    enum:
      - H
      - V
  calibration:
    enum:
        - brightness_temperature
        - radiance
        - counts
    transitive: true
  modifiers:
    required: true
    default: []
    type: !!python/name:satpy.dataset.ModifierTuple
```
