### ISSUE TITLE
Loading and resampling composites sometimes discards their dependencies

### ISSUE THREAD

**Issue by mraspaud** [pytroll/satpy#1443]
**Describe the bug**
When loading two composites, with one depending on the other, and resampling them, sometimes the depency composite never makes it to the resulting resampled area. 

**To Reproduce**

```python
    from satpy.scene import Scene
    from satpy import find_files_and_readers

    path_data = '/home/a001673/data/satellite/viirs/sdr/noaa20_20200318_1030_12075'
    files = find_files_and_readers(base_dir=path_data,
                                   reader='viirs_sdr')
    print("Reading files...")
    scn = Scene(filenames=files)

    composites = ['overview', 'overview_with_cloudtop']
    scn.load(composites, generate=False)

    lscn = scn.resample('eurol')
    lscn2 = scn.resample('euro4')
    try:
        assert 'overview' in lscn2
    finally:
        print(lscn2.keys())

```

```yaml
  overview_with_cloudtop:
    compositor: !!python/name:satpy.composites.DayNightCompositor
    standard_name: overview_with_cloudtop
    prerequisites:
      - overview
      - cloudtop
      - solar_zenith_angle

```

**Expected behavior**
I expect that assertion to hold, ie that 'overview' will always be present in `lscn2`

**Actual results**
About 50% of the time on my computer the above script raises an `AssertionError`, meaning the 'overview' composite never makes it to lscn2.

**Environment Info:**
 - OS: Linux
 - Satpy Version: master
 - PyResample Version: 1.17.0
