### ISSUE TITLE
Make it possible to have different stretch methods for each channel of a composite

### ISSUE THREAD

**Issue by pnuu** [pytroll/satpy#1455]
## Feature Request

**Is your feature request related to a problem? Please describe.**
As discussed on [Slack](https://pytroll.slack.com/archives/CK9TPLCG0/p1605885244107600) with @ameraner , there should be a way to apply different stretching methods for different channels in a composite. This would be similar to the `invert` method which can be applied to specific channels with

```yaml
  operations:
  - name: inverse
    method: !!python/name:satpy.enhancements.invert
    args:
    - [false, false, true]
```

**Describe the solution you'd like**
Something like this maybe?

```yaml
  operations:
    - name: linear_stretch_r_channel
      method: !!python/name:satpy.enhancements.stretch
      kwargs: {stretch: linear, channels: [true, false, false]}
    - name: histogram_stretch_gb_channels
      method: !!python/name:satpy.enhancements.stretch
      kwargs: {stretch: histogram, channels: [false, true, true]}
```

Currently the `stretch` method behaves like using `kwargs: {..., channels: [true, true, true]}`.

**Describe any changes to existing user workflow**
Only a new possibilitity for the user.

**Additional context**
Currently this can be done in the following way:

1. create single-channel sub-composites for each of the end product composite
2. add enhancements for each of the sub-composites with the wanted stretchings
3. create the main composite
4. create enhnacement for the main composite with crude stretch from 0 to 1 for each channel
