### ISSUE TITLE
Inconsistent naming of optional datasets in composite configs and compositors

### ISSUE THREAD

**Issue by pnuu** [pytroll/satpy#160]
#### Code Sample, a minimal, complete, and verifiable piece of code

```yaml
# visir.yaml
  nir_reflectance:
    compositor: !!python/name:satpy.composites.NIRReflectance
    prerequisites:
    - 11
    optional_prerequisites:
    - solar_zenith_angle
    - 13.4
```

```python
# composites/__init__.py
class NIRReflectance(CompositeBase):

    def __call__(self, projectables, optional_datasets=None, **info):
        pass
```

#### Problem description

For optional datasets the naming is different in the YAML configuration files for the compositors compared to the variables used in the compositors.

#### Versions of Python, package at hand and relevant dependencies
All SatPy versions.
