### ISSUE TITLE
Missing area attribute in exported netcdf file

### ISSUE THREAD

**Issue by zxdawn** [pytroll/satpy#1688]
**Describe the bug**
The area attribute is missing in the exported NetCDF file.

**To Reproduce**

```python
import xarray as xr
from glob import glob
from satpy import Scene
scn = Scene(glob('OR_ABI-L1b-RadC-M6C13_G16_s20201530*.nc'), reader='abi_l1b')
scn.load(['C13'])
scn.save_dataset('C13', filename='test_single.nc')
ds = xr.open_dataset('test_single.nc')
print(ds['C13'].attrs['area'])
```

**Actual results**
```
No time dimension in datasets, skipping time bounds creation.
Traceback (most recent call last):
  File "test_area.py", line 10, in <module>
    print(ds['C13'].attrs['area'])
KeyError: 'area'
```

**Environment Info:**
 - OS:  Linux
 - Satpy Version: 0.28.1
 - PyResample Version: 1.19.0

**Comment by djhoese** [comment]
This is a duplicate of #1672. If you add `include_lonloats=False` to your `save_dataset` call then the grid_mapping attributes and variable should be added properly. The problem is the CF reader doesn't actually do anything with that right now. Pull requests are welcome if you want to implement it.

**Comment by djhoese** [comment]
Oh I also see that you are doing `xr.open_dataset`, I don't think that would have ever preserved the AreaDefinition object. Satpy will need to do the reading (at least for now) to get any pyresample geometry information (a swath definition).

**Comment by zxdawn** [comment]
@djhoese Thanks for the answer. Then, do I need to save the area as file for later calculation of lon/lat? or can I get the lon/lat from the exported nc file directly?

**Comment by djhoese** [comment]
Your options are:

1. Use the default `include_lonlats=True` and load the file with either Satpy or xr.open_dataset. With the satpy reader you should get a SwathDefinition which you can call `get_lonlats()` on. With open_dataset, you should get a longitude and latitude variable.
2. Update the Satpy CF **reader** to handle the grid_mapping information and produce an AreaDefinition so you can then do `get_lonlats()` on it.

**Comment by zxdawn** [comment]
@djhoese As I need to save many files, the first method is neglected.

I tried other two methods: `load_cf_area` and `area.yaml`.

## load_cf_area

```
from pyresample.utils import load_cf_area
area_def, cf_info = load_cf_area('./test_single.nc', variable='GOES-East', x='x', y='y')
lon, lat = area_def.get_lonlats()
```
This produces wrong lon and lat ....
![image](https://user-images.githubusercontent.com/30388627/119348926-12d37700-bcd0-11eb-9e25-1f4201dd290e.png)

## area.yaml

```
from pyresample import load_area
import yaml
scn['C13'].area.dump('area.yaml')
area_def = load_area('area.yaml', 'GOES-East')
```

Error:
```
ConstructorError: could not determine a constructor for the tag 'tag:yaml.org,2002:python/object/apply:numpy.core.multiarray.scalar'
  in "area.yaml", line 18, column 7
```

It seems the exported yaml file has some stange strings:
```
GOES-East:
  description: 2km at nadir
  projection:
    proj: geos
    sweep: x
    lon_0: -75
    h: 35786023
    x_0: 0
    y_0: 0
    ellps: GRS80
    no_defs: null
    type: crs
  shape:
    height: 1500
    width: 2500
  area_extent:
    lower_left_xy:
    - !!python/object/apply:numpy.core.multiarray.scalar
      - &id001 !!python/object/apply:numpy.dtype
        args: [f8, false, true]
        state: !!python/tuple [3, <, null, null, null, -1, -1, 0]
      - !!binary |
        valIpYOsS8E=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        EDtTqEUoOEE=
    upper_right_xy:
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        C5jA7XMZNUE=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        GLK65aOBUUE=
    units: m
```
