### ISSUE TITLE
What shoud I do if I only want to keep the day part of DayNightCompositor?

### ISSUE THREAD

**Issue by yukaribbba** [pytroll/satpy#1780]
Just to leave the night part blank (alpha channel)
For example:

```
  daynight:
    compositor: !!python/name:satpy.composites.DayNightCompositor
    prerequisites:
      - name: day
      - name: ?????
```
