### ISSUE TITLE
Raised RuntimeError when trying to make HIMAWARI-8 true color image

### ISSUE THREAD

**Issue by BigShuiTai** [pytroll/satpy#2127]
**Describe the bug**
I was trying to make a HIMAWARI-8 true color image. However, SatPy module raised a ```RuntimeError``` to me at ```_slice_data``` function.

**To Reproduce**

```python
# Your code here
def get_area_def_format(proj, georange, res):
    min_lon, max_lon, min_lat, max_lat = georange
    left = min_lon
    right = max_lon
    up = min_lat
    down = max_lat
    res = res * 1000
    lat_0 = (up + down) / 2
    lon_0 = (right + left) / 2
    
    from pyproj import Proj
    p = Proj(proj=proj, lat_0=lat_0, lon_0=lon_0, ellps="WGS84")
    
    left_ex1, up_ex1 = p(left, up)
    right_ex1, up_ex2 = p(right, up)
    left_ex2, down_ex1 = p(left, down)
    right_ex2, down_ex2 = p(right, down)
    left_ex3, dummy = p(left, lat_0)
    right_ex3, dummy = p(right, lat_0)
    
    area_extent = (min(left_ex1, left_ex2, left_ex3),
                   min(up_ex1, up_ex2),
                   max(right_ex1, right_ex2, right_ex3),
                   max(down_ex1, down_ex2))
    
    xsize = int(round((area_extent[2] - area_extent[0]) / res))
    ysize = int(round((area_extent[3] - area_extent[1]) / res))
    
    return lat_0, lon_0, xsize, ysize, area_extent

channel = "true_color"

scn = Scene(glob.glob("./HS_H08*.DAT.bz2"), reader='ahi_hsd')
scn.load([channel])

georange = (32.5, 47.5, 112.5, 127.5)
latmin, latmax, lonmin, lonmax = georange

from pyresample import get_area_def
area_id = 'TEST01'
lat_0, lon_0, x_size, y_size, area_extent = get_area_def_format("eqc", (lonmin, lonmax, latmin, latmax), 1)
projection = f'+proj=eqc +lat_0={lat_0} +lon_0={lon_0} +ellps=WGS84'
description = 'TEST01'
proj_id = f'eqc_{lat_0}_{lon_0}'
areadef = get_area_def(area_id, description, proj_id, projection, x_size, y_size, area_extent)
new_scn = scn.resample(areadef)
new_scn.save_dataset(channel, base_dir="./true_color/", filename=f"{args.system}_true_color.png")
```

**Expected behavior**
Succeed in compositing true color image and save it in certain folder.

**Actual results**
```python
# For these results below I have used these codes in ```_slice_data```:
# print(slice_x, slice_y)
# print(('x', source_area.width), ('y', source_area.height), dataset.sizes.items())
slice(3082, 4582, None) slice(1109, 2253, None)
('x', 1500) ('y', 1144) ItemsView(Frozen({'y': 1144, 'x': 1500}))
slice(3082, 4582, None) slice(1109, 2253, None)
('x', 1500) ('y', 1144) ItemsView(Frozen({'y': 1144, 'x': 1500}))
slice(3082, 4582, None) slice(1109, 2253, None)
('x', 1500) ('y', 1144) ItemsView(Frozen({'y': 1144, 'x': 1500}))
slice(6165, 9163, None) slice(2218, 4506, None)
('x', 2998) ('y', 2288) ItemsView(Frozen({'y': 2288, 'x': 2998}))
slice(6165, 9163, None) slice(2218, 4506, None)
('x', 2998) ('y', 2288) ItemsView(Frozen({'y': 2288, 'x': 2998}))
slice(6165, 9163, None) slice(2218, 4506, None)
('x', 2998) ('y', 2288) ItemsView(Frozen({'y': 2288, 'x': 2998}))
slice(3082, 4582, None) slice(1109, 2253, None)
('x', 1500) ('y', 1144) ItemsView(Frozen({'y': 1144, 'x': 1500}))
slice(3082, 4582, None) slice(1109, 2253, None)
('x', 1500) ('y', 1144) ItemsView(Frozen({'y': 0, 'x': 1500}))
Traceback (most recent call last):
  File "/www/wwwroot/Satima/satpy_ahi_true_color.py", line 271, in <module>
    Satpy()
  File "/www/wwwroot/Satima/satpy_ahi_true_color.py", line 59, in __init__
    self.ask_root()
  File "/www/wwwroot/Satima/satpy_ahi_true_color.py", line 150, in ask_root
    datas = self.extract(roots, center_lon, center_lat, self.georange, args.channel, names)
  File "/www/wwwroot/Satima/satpy_ahi_true_color.py", line 190, in extract
    new_scn = scn.resample(areadef)
  File "/root/miniconda3/lib/python3.9/site-packages/satpy/scene.py", line 908, in resample
    self._resampled_scene(new_scn, destination, resampler=resampler,
  File "/root/miniconda3/lib/python3.9/site-packages/satpy/scene.py", line 819, in _resampled_scene
    dataset, source_area = self._reduce_data(dataset, source_area, destination_area,
  File "/root/miniconda3/lib/python3.9/site-packages/satpy/scene.py", line 869, in _reduce_data
    dataset = self._slice_data(source_area, (slice_x, slice_y), dataset)
  File "/root/miniconda3/lib/python3.9/site-packages/satpy/scene.py", line 783, in _slice_data
    raise RuntimeError
RuntimeError
```

**Environment Info:**
 - OS: Ubuntu 20.04.4 LTS x86_64
 - Satpy Version: 0.35.0
 - PyResample Version: 1.23.0
 - PyProj Version: 3.3.0

**Additional context**
Additionally, I found that it sometimes succeed if I ran the code again.

**Comment by djhoese** [comment]
Thanks for filing this issue. It is unfortunate how unhelpful that error is. Thanks for that print out it is really helpful. So it seems some input has a size of 0 for the `y` dimension. Could you add to your print statement `dataset.attrs["_satpy_id"]` and let us know what the new output is?

This will tell us which dataset has 0 rows and maybe give us an idea what is going on.

**Comment by djhoese** [comment]
Hm. So with the same input data sometimes it succeeds and sometimes it fails?

In your original script you had that you were loading `true_color`, but this new print out shows the use of `green_nocorr`. That version of the green composite shouldn't be used for `true_color`. Did you make some modifications to the composites?

**Comment by BigShuiTai** [comment]
> Hm. So with the same input data sometimes it succeeds and sometimes it fails?
> 
> In your original script you had that you were loading `true_color`, but this new print out shows the use of `green_nocorr`. That version of the green composite shouldn't be used for `true_color`. Did you make some modifications to the composites?

Ah I have forgot to tell you that I used ```true_color_hybrid``` composite method which was written by @[WP19](https://github.com/WP19VFF):
```yaml
# true_color_hybrid
  green_nocorr:
    compositor: !!python/name:satpy.composites.ahi.GreenCorrector
    prerequisites:
      - name: B02
      - name: B04
    standard_name: toa_reflectance
    fractions: [0.93, 0.07]
  true_color:
    compositor: !!python/name:satpy.composites.GenericCompositor
    prerequisites:
    - name: B03
      modifiers: [sunz_corrected, no_aerosol_rayleigh_corrected]
    - name: green
    - name: B01
      modifiers: [sunz_corrected, no_aerosol_rayleigh_corrected]
    high_resolution_band: red
    standard_name: true_color
  true_color_nocorr:
    compositor: !!python/name:satpy.composites.GenericCompositor
    prerequisites:
    - name: B03
    - name: green_nocorr
    - name: B01
    high_resolution_band: red
    standard_name: true_color
  true_color_hybrid:
    compositor: !!python/name:satpy.composites.DayNightCompositor
    standard_name: true_color_hybrid
    prerequisites:
      - true_color
      - true_color_nocorr
```
