### ISSUE TITLE
Add support for reducing Rayleigh correction at large solar zenith angles

### ISSUE THREAD

**Issue by strandgren** [pytroll/satpy#2288]
## Feature Request

When applying Rayleigh correction using pyspectral, there is a build in function for reducing the correction as large solar zenith angles because the RTM/correction breaks down. See
- https://github.com/pytroll/pyspectral/blob/main/pyspectral/rayleigh.py#L287
- https://github.com/pytroll/pyspectral/pull/141.

There is, however, no interface to this Rayleigh correction reduction from Satpy. Hence, this is a feature request to add this.

**Describe the solution you'd like**
Ideally add a keyword argument to `PSPRayleighReflectance` saying whether the reduction at large solar zenith angle shall be applied or not. E.g. something like this:

```
class PSPRayleighReflectance(ModifierBase):
    """Pyspectral-based rayleigh corrector for visible channels."""

    def __call__(self, projectables, optional_datasets=None, **info):
        """Get the corrected reflectance when removing Rayleigh scattering.

    # Code for applying Rayleigh correction

    reduce_reyleigh= self.attrs.get('reduce_reyleigh', False)
    if reduce_reyleigh:
        refl_cor_band  = reduce_rayleigh_highzenith(sunz, refl_cor_band, thresh_zen, maxzen, strength)

    # Remove from measured reflectance and return
```
In that case one could define the Rayleigh correction in yaml-file like this:
```
modifiers:
  rayleigh_corrected:
    modifier: !!python/name:satpy.modifiers.PSPRayleighReflectance
    atmosphere: us-standard
    aerosol_type: rayleigh_only
    reduce_rayleigh: True
    prerequisites:
    - name: B03
      modifiers: [sunz_corrected]
    optional_prerequisites:
    - satellite_azimuth_angle
    - satellite_zenith_angle
    - solar_azimuth_angle
    - solar_zenith_angle
```

**Describe any changes to existing user workflow**
Currently, the `reduce_rayleigh_highzenith` takes three input arguments that control how strongly to reduce the Rayleigh correction: `thresh_zen`, `maxzen` and `strength`. These might have to be converted to keyword arguments in order to allow for some default values. Still it is not entirely clear to me at this point, how these tuning parameters could be modified in a yaml-file modifier where the Rayleigh correction is defined.
