### ISSUE TITLE
Runtime deprecation warning is thrown for compositor that is not used

### ISSUE THREAD

**Issue by strandgren** [pytroll/satpy#2363]
**Describe the bug**
While loading AHI channel data, a RuntimeWarning is thrown with a deprecation warning for a compositor that is not needed/used for the requested dataset.

**To Reproduce**

```python
from satpy import Scene
scn = Scene(filenames=[<list_of_AHI_files>], reader='ahi_hsd')
scn.load('B03')
```

**Expected behavior**
The dataset 'B03' is loaded without any deprecation warning about independent/unrelated composites/compositors.

**Actual results**
```
DEBUG satpy.readers.yaml_reader Line 112: Reading ('/tcenas/home/strandgren/git/ext/py/satpy/latest/satpy/satpy/etc/readers/ahi_hsd.yaml',)
DEBUG satpy.readers.yaml_reader Line 605: Assigning to ahi_hsd: ['/tcenas/proj/optcalimg/andream/nonEUMsat/AHI_202001300300/hsd/HS_H08_20200130_0300_B01_FLDK_R10_S0110.DAT']
INFO pysat.data_loader Line 112: No dataset configuration file available for ahi_hsd
INFO pysat.data_loader Line 67: loading satpy Scene object
DEBUG satpy.readers.yaml_reader Line 112: Reading ('/tcenas/home/strandgren/git/ext/py/satpy/latest/satpy/satpy/etc/readers/ahi_hsd.yaml',)
DEBUG satpy.readers.yaml_reader Line 605: Assigning to ahi_hsd: [<LONG_LIST_OF_FILENAMES>]
DEBUG satpy.composites.config_loader Line 269: Looking for composites config file ahi.yaml
DEBUG satpy.composites.config_loader Line 269: Looking for composites config file visir.yaml
/tcenas/home/strandgren/git/ext/py/satpy/latest/satpy/satpy/composites/spectral.py:177: RuntimeWarning: 'GreenCorrector' is deprecated, use 'SpectralBlender' instead, or 'HybridGreen' for hybrid green correction following Miller et al. (2016).
```

**Additional context**
While introducing new green band corrections for AHI and FCI in #2280, the code as well as the pre-configured composite names (in `etc/composites/ahi.yaml`) where refactored in order to have a better and more generic yet descriptive naming convention. To ensure backward compatibility, the names of the old composites were kept, but pointing to the old method that throws a runtime deprecation warning, in order to alert the user to use another composite name, which is also explained in the corresponding yaml-entries. An example of this is shown below.

Old `green` composite kept for backward compatibility, using the `GreenCorrector` compositor in order to trigger a deprecation warning and including a comment to use the new equivalent composite `hybrid_green` instead:
```
# from etc/composites/ahi.yaml
  green:
    # Deprecated green composite using deprecated class 'GreenCorrector'. Use 'hybrid_green' instead.
    compositor: !!python/name:satpy.composites.spectral.GreenCorrector
    # FUTURE: Set a wavelength...see what happens. Dependency finding
    #         probably wouldn't work.
    prerequisites:
      # should we be using the most corrected or least corrected inputs?
      # what happens if something requests more modifiers on top of this?
      - wavelength: 0.51
        modifiers: [sunz_corrected, rayleigh_corrected]
      - wavelength: 0.85
        modifiers:  [sunz_corrected]
    standard_name: toa_bidirectional_reflectance
```

New equivalent composite called `hybrid_green`, using the refactored compositor `HybridGreen`.
```
# from etc/composites/ahi.yaml
  hybrid_green:
    compositor: !!python/name:satpy.composites.spectral.HybridGreen
    # FUTURE: Set a wavelength...see what happens. Dependency finding
    #         probably wouldn't work.
    prerequisites:
    # should we be using the most corrected or least corrected inputs?
    # what happens if something requests more modifiers on top of this?
    - wavelength: 0.51
      modifiers: [sunz_corrected, rayleigh_corrected]
    - wavelength: 0.85
      modifiers: [sunz_corrected]
    standard_name: toa_bidirectional_reflectance
```

**Potential solutions:**
We could either have the deprecated composites point to the new compositors, like e.g. the `HybridGreen`. This would remove the deprecation warning, but still keep the workflow and functionality untouched. However, the user would not get alerted that it is using a deprecated composite which was the initial idea of using the deprecated compositors here.

Alternatively, one could consider why Satpy checks all composites (and thus catches the deprecation warnings) for a given instrument if an unrelated dataset is loaded. In my opinion it would be cleaner if only the dataset or composite (and potential composites it may depend on) that the user is loading would be checked.
