### ISSUE TITLE
Combine the strengths of CategoricalDataCompositor and MaskingCompositor

### ISSUE THREAD

**Issue by gerritholl** [pytroll/satpy#2401]
## Feature Request

**Is your feature request related to a problem? Please describe.**

We are currently using the MaskingCompositor to add to our imagery data a mask derived from the NWCSAF Cloud Type, similar to the built-in `vis_with_ir_cloud_overlay` composite.  This produces a composite dataset with dimensions `[bands, y, x]`.  We would like to write the result as a NetCDF file, where the imagery and the mask are different data variables.  Rather than having one data variable with `[bands, y, x]` (where the dimension `bands` has length 2), we would like two data variables, each with dimensions `[y, x]`.

It seems the `CategoricalDataCompositor` can do this, but this has a less user-friendly interface.  In the `CategoricalDataCompositor`, users must pass a look-up table as an array with numerical values for each possible input value.  In the `MaskingCompositor`, users can refer to labels included in the metadata of the input data.  This means that a composite defined as

```yaml

  dwd_vis_with_ir_cloud_overlay:
    compositor: !!python/name:satpy.composites.MaskingCompositor
    standard_name: dwd_vis_with_ir_cloud_overlay
    prerequisites:
    - dwd_vis_with_ir
    - ct
    # Default is opaque (transparency = 0)
    conditions:
      - method: equal
        value: Cloud-free_land
        transparency: 100
      - method: equal
        value: Cloud-free_sea
        transparency: 100
      - method: equal
        value: Snow_over_land
        transparency: 100
      - method: equal
        value: Sea_ice
        transparency: 100
      - method: equal
        value: Fractional_clouds
        transparency: 100
      - method: equal
        value: High_semitransparent_thin_clouds
        transparency: 100
      - method: equal
        value: High_semitransparent_above_snow_ice
        transparency: 100
      - method: equal
        value: 255
        transparency: 100
    mode: LA
```

becomes instead

```yaml
  dwd_nwcsaf_cloud_mask:
    compositor: !!python/name:satpy.composites.CategoricalDataCompositor
    prerequisites:
      - ct
    standard_name: dwd_nwcsaf_cloud_mask
    lut: [0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0]
```

The dataset returned by the second example is identical to the one added to band `A` in the first example (if we pass `generate=False`; see #2400), but the first version is much more user-friendly and maintainable.

**Describe the solution you'd like**

I would like that I'm able to get a separate dataset, like with the `CategoricalDataCompositor`, but with the user friendly conditions table as for the `MaskingCompositor`.

**Describe any changes to existing user workflow**

This should be possible without breaking any existing functionality.

**Additional context**

Apart from providing a separate dataset, I don't know what the `CategoricalDataCompositor` can do that the `MaskingCompositor` cannot.
