### ISSUE TITLE
combine metadata in `MultiFiller`

### ISSUE THREAD

**Issue by gerritholl** [pytroll/satpy#2446]
## Feature Request

**Is your feature request related to a problem? Please describe.**

We use `MultiFiller` to produce a world composite satellite image.  In a first step, we project full disc images from the different geostationary satellites onto a plate carrée world map.  In a second step, we read those files and combine them using a composite based on the `MultiFiller` compositor, such as:

```
  world_comp:
    compositor: !!python/name:satpy.composites.MultiFiller
    prerequisites:
    - name: zds
    optional_prerequisites:
    - name: goes_west
    - name: goes_east
    - name: iodc
    - name: himawari
    standard_name: world_comp
```

This works, but the metadata for the resulting composite are coming entirely from zds.  When zds has a start time of 10:15, but goes and himawari have 10:10, the resulting composite still has a start time of 10:15.  This is confusing.

**Describe the solution you'd like**

To get the "correct" start time in our world composite, we would need:

- that the `MultiFiller` composite optionally not only fills, but also combines the metadata; the compositor would need to be able to pass parameters to `combine_metadata` for optimal user control; and
- that combining time metadata allows for taking the minimum rather than the average or first value of the start time (see #2447)

**Describe any changes to existing user workflow**

The default behaviour would be the status quo.  Therefore, there should be no changes to existing user workflow.

**Additional context**

- Alternative 1: We could define our world composite with goes_east as the prerequisite and zds as an optional prerequisite.  This is not optimal, because we generate an (incomplete) world composite even if goes_east is missing (but not when zds is missing).
- Alternative 2: We wait for FCI and the problem disappears.
