### ISSUE TITLE
Add "References"-column to Satpy's Documentation Reader-table

### ISSUE THREAD

**Issue by sjoro** [pytroll/satpy#2475]
## Feature Request

**Is your feature request related to a problem? Please describe.**

Browsing Satpy's documentation I often find myself checking the available readers-table:
https://satpy.readthedocs.io/en/stable/index.html#id1

<img width="1132" alt="Screenshot 2023-05-10 at 17 23 57" src="https://github.com/pytroll/satpy/assets/36533519/064f7ca7-0875-4a72-b2a8-8c9413c26f31">

It would be nice to have an extra column after `fsspec support` to have link(s) to relevant format spec or resources which would be helpful with the reader. Some reader's offer References in their respective module, e.g. [`seviri_l1b_hrit`](https://satpy.readthedocs.io/en/stable/api/satpy.readers.seviri_l1b_hrit.html) and [`seviri_l1b_native`](https://satpy.readthedocs.io/en/stable/api/satpy.readers.seviri_l1b_native.html), but this is a bit more work to dig out in the documentation through `readthedocs`. Extra column in the table would give a quick and easy way to find relevant documentation for the reader.

Caveats to this proposal are, of course, 
1) not all the readers have a reference document listed in the respective reader-module, so for many readers this column would be empty... probably for a long time.
2) in general, keeping links up-to-date is next to impossible, which might frustrate users if the links are not working.
3) more work on Satpy-devs to add these references to respective reader yaml-file... could be potentially be spread out to multiple contributors by requiring a reference to be added if a PR is coming in for a certain reader.
4) readers for future instruments don't typically have publicly available documentation until very close to launch
5) what to do if there are multiple references/resources available? will the table be horrible to read?!?

**Describe the solution you'd like**
Extra column in Satpy available readers-table for relevant documentation for the reader.

**Describe any changes to existing user workflow**
None. reader yaml-files would need to be updated with a `reference` or `resource`-tag, e.g.
```
reader:
  name: seviri_l1b_hrit
  short_name: SEVIRI L1b HRIT
  long_name: MSG SEVIRI Level 1b (HRIT)
  description: >
    HRIT reader for EUMETSAT MSG (Meteosat 8 to 11) SEVIRI Level 1b files.
  status: Nominal
  supports_fsspec: true
  sensors: [seviri]
  default_channels: [HRV, IR_016, IR_039, IR_087, IR_097, IR_108, IR_120, IR_134, VIS006, VIS008, WV_062, WV_073]
  reader: !!python/name:satpy.readers.yaml_reader.GEOSegmentYAMLReader
  reference: https://www-cdn.eumetsat.int/files/2020-04/pdf_fg15_msg-native-format-15.pdf
``` 

`reader_table.generate_reader_table` would need to be updated to pull this extra info to the table.

Just a suggestion, to get discussion going
