### ISSUE TITLE
Reprojected image cut off at 180E

### ISSUE THREAD

**Issue by crazyapril** [pytroll/satpy#3000]
**Describe the bug**
I have a flat night light map (in EPSG:4326), and I want to reproject it to a satellite view. However, the reprojected image gets cut off at 180E. Obviously it's not wanted.
![image](https://github.com/user-attachments/assets/6379aa7c-9910-4baa-b5d0-c2ad75f80f7f)

What could go wrong?

**To Reproduce**

```python
from satpy.resample import get_area_def
from satpy.scene import Scene

blackmarble = Scene(reader="generic_image",
                    filenames=["recipes/BlackMarble.tiff"])
blackmarble.load(["image"])
res = blackmarble.resample(get_area_def("himawari9"), resampler="nearest")
res.save_dataset("image", "recipes/h9-night.tif", writer="geotiff")
```

And area def `himawari9`:
```yaml
himawari9:
  description: Himawari-9 B03
  projection:
    proj: geos
    lon_0: 140.7
    h: 35785863
    x_0: 0
    y_0: 0
    a: 6378137
    rf: 298.257024882273
    no_defs: null
    type: crs
  shape:
    height: 22000
    width: 22000
  area_extent:
    lower_left_xy: [-5499999.968358421, -5499999.96835842]
    upper_right_xy: [5499999.968358421, 5499999.968358421]
    units: m
```
