### ISSUE TITLE
SEVIRI. Where is built-in composite group_radiance_alpha defined?

### ISSUE THREAD

**Issue by gonzobard777** [pytroll/satpy#3098]
I was interested in composite `hrv_group_radiance` after reviewing [built-in compositors available in Satpy for SEVIRI](https://github.com/pytroll/satpy/blob/main/satpy/etc/composites/seviri.yaml).

[link to hrv_group_radiance in source](https://github.com/pytroll/satpy/blob/main/satpy/etc/composites/seviri.yaml#L666C3-L666C21)
```yaml
  hrv_group_radiance:
    compositor: !!python/name:satpy.composites.BackgroundCompositor
    standard_name: imager_with_lightning
    prerequisites:
      - group_radiance_alpha
      - HRV
```
I loaded all the satellite channels, but this composite was not in the list of available ones.
I started to understand the reason and it turned out that the prerequisites composite `group_radiance_alpha` was not described at all.

Please tell me if this is a mistake?
If not, then where can I get the description of the **group_radiance_alpha** composite?
