### ISSUE TITLE
Custom composite for reader 'generic_image'

### ISSUE THREAD

**Issue by gonzobard777** [pytroll/satpy#3108]
I want to create a composite for reader `generic_image` to invert the original geotiff(inversion of the plan to do in the enhancer).
To describe a composite I create a `generic_image.yaml` file and place it in the composite folder:
![Image](https://github.com/user-attachments/assets/50510c0e-436c-4d4d-8dba-262f40a5a804)
File content of `generic_image.yaml`:
```yaml
sensor_name: images

composites:
  inverted_image:
    compositor: !!python/name:satpy.composites.GenericCompositor
    prerequisites:
      - image
    standard_name: inverted_image
```
Now I want to see what datasets are available to me:
```python
config.set(config_path=['D:\\satpy_config'])
scn = Scene(reader='generic_image', filenames=['D:\\a1_20250401110000_ch04.tif'])
all_datasets = scn.available_dataset_names(composites=True)
```
and unfortunately, command `scn.available_dataset_names(composites=True)` returns only the following available datasets: `['image']`

Could you please tell me how can I define a custom composite for reader `generic_image`?
