### ISSUE TITLE
Creating day/night composites

### ISSUE THREAD

**Issue by hany** [pytroll/satpy#460]
Hi there,

I'm not sure if this is possible, but is there a way to produce day and night composites via GOES-16 ABI to create an image similar to this?

https://cdn.star.nesdis.noaa.gov/GOES16/ABI/FD/GEOCOLOR/20182831245_GOES16-ABI-FD-GEOCOLOR-1808x1808.jpg

The description of "GeoColor" is:

> GeoColor is a multispectral product composed of True Color (using a simulated green component) during the daytime, and an Infrared product that uses bands 7 and 13 at night. During the day, the imagery looks approximately as it would appear when viewed with human eyes from space. At night, the blue colors represent liquid water clouds such as fog and stratus, while gray to white indicate higher ice clouds, and the city lights come from a static database that was derived from the VIIRS Day Night Band.

Any help would be appreciated! Thanks for maintaining such a robust and useful project!

**Comment by djhoese** [comment]
I think @pnuu is doing something very similar to this already and has also created the `DayNightCompositor` class. He could maybe show you his example, but here is one of the existing ones in `composites/visir.yaml`:

```yaml
  natural_with_night_fog:
    compositor: !!python/name:satpy.composites.DayNightCompositor
    standard_name: natural_with_night_fog
    prerequisites:
      - natural_color
      - night_fog
      - solar_zenith_angle
```

So this is using the `natural_color` RGB in the day time, `night_fog` composite in the night time, and using the existing (optional) `solar_zenith_angle` dataset to determine day and night time.

**Comment by pnuu** [comment]
I think we don't (yet?) have a compositor that would use an pre-made image as a background. There is a compositor (`CloudCompositor`) that can be used to isolate the high cold clouds, and then colorized (`colorize` enhancement). Not sure how to isolate the low clouds, but if you find out how to do that (PRs wellcome!), then you can also colorize them. Maybe it's better to create a new compositor for the low/high clouds.

The background compositor is an interesting one. I'm not yet sure how to pass the filename from the YAML config so that everything would still work. Maybe via enhancement? I might take a closer look at this, if I find the time.

When all the separate pieces (composites) are together, they can be put together:

```yaml
  geo_color_night:
    standard_name: geo_color_night
    # This compositor doesn't exist yet
    compositor: !!python/name:satpy.composites.BackgroundCompositor
    # Use in-line compositing
    prerequisites:
      # The BackgroundCompositor needs to read an image, not sure how that should be configured somewhere. Maybe in the enhancements. I'll add a placeholder here
      # filename: - /path/to/static/night/image.tif
      # This compositor doesn't exist yet
      - compositor: !!python/name:satpy.composites.HighLowCloudCompositor
        prerequisites:
        - something
        - something_other
        - maybe_even_something_more

  geo_color:
    compositor: !!python/name:satpy.composites.DayNightCompositor
    standard_name: geo_color
    prerequisites:
      - true_color
      - geo_color_night
      - solar_zenith_angle
```
