### ISSUE TITLE
OMPS NPP NMSO2

### ISSUE THREAD

**Issue by bbakernoaa** [pytroll/satpy#57]
I'm a newer user to satpy and am having trouble loading some OMPS data downloaded from the NASA EarthData website.  The files names are as follows: 

> OMPS-NPP_NMSO2-L2_2017m0707t235247_o29505_2017m0708t125922.h5

I thought that I would need to modify the omps_edr.yaml file to address this but I continue to get an error when trying to load it like so
```python
gs = Scene(platform_name='NPP',sensor='omps',filenames=files)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-7-2d834f8862df> in <module>()
----> 1 gs = Scene(platform_name='NPP',sensor='OMPS',filenames=files)

/data/aqf2/barryb/anaconda2/lib/python2.7/site-packages/satpy/scene.py in __init__(self, filenames, ppp_config_dir, reader, base_dir, sensor, start_time, end_time, area, reader_kwargs, **metadata)
     99                                                     base_dir=base_dir,
    100                                                     reader=reader,
--> 101                                                     reader_kwargs=reader_kwargs)
    102         self.info.update(self._compute_metadata_from_readers())
    103         self.datasets = DatasetDict()

/data/aqf2/barryb/anaconda2/lib/python2.7/site-packages/satpy/scene.py in create_reader_instances(self, filenames, base_dir, reader, reader_kwargs)
    145                       sensor=self.info.get("sensor"),
    146                       filenames=filenames,
--> 147                       reader_kwargs=reader_kwargs)
    148 
    149     @property

/data/aqf2/barryb/anaconda2/lib/python2.7/site-packages/satpy/readers/__init__.pyc in __call__(self, filenames, sensor, reader, reader_kwargs)
    350                     remaining_filenames)))
    351         if not reader_instances:
--> 352             raise ValueError("No supported files found")
    353         return reader_instances
    354 

ValueError: No supported files found
```

**Comment by davidh-ssec** [comment]
The OMPS reader was created as sort of a proof-of-concept so it may have limited functionality from what you expect. It was also my first time working with OMPS data so I may have done something wrong. As you can see in the omps_edr.yaml file we currently only support the following filename scheme for SO2:

```
OMPS-NPP-TC_EDR_SO2NRT-%Ym%m%dt%H%M%S-o00001-%Ym%m%dt%H%M%S.he5
```

Do you have any idea what the differences are between your file and the above type of file?

**Comment by bbakernoaa** [comment]
I may be wrong but isn't there two types of files in there

```
file_types:
  omps_tc_so2_edr:
    file_reader: !!python/name:satpy.readers.omps_edr.EDREOSFileHandler
    file_patterns: ['{instrument_shortname}-{platform_shortname}-TC_EDR_SO2NRT-{start_time:%Ym%m%dt%H%M%S}-o{orbit:05d}-{end_time:%Ym%m%dt%H%M%S}.he5']
  omps_tc_to3_edr:
    file_reader: !!python/name:satpy.readers.omps_edr.EDRFileHandler
    file_patterns: ['{instrument_shortname}-{platform_shortname}-TC_EDR_TO3-{version}-{start_time:%Ym%m%dt%H%M%S}-o{orbit:05d}-{end_time:%Ym%m%dt%H%M%S}.h5']
```
I had tried to modify it to the following:

```file_types:
  omps_tc_so2_edr:
    file_reader: !!python/name:satpy.readers.omps_edr.EDREOSFileHandler
    file_patterns: ['{instrument_shortname}-{platform_shortname}-TC_EDR_SO2NRT-{start_time:%Ym%m%dt%H%M%S}-o{orbit:05d}-{end_time:%Ym%m%dt%H%M%S}.he5']
  omps_tc_to3_edr:
    file_reader: !!python/name:satpy.readers.omps_edr.EDRFileHandler
    file_patterns: ['OMPS_NPP_NMSO2-L2_{start_time:%Ym%m%dt%H%M%S}_o{orbit:05d}_{end_time:%Ym%m%dt%H%M%S}.h5']
```

Simply opening it with h5py 

```python

In [26]: f['GeolocationData'].keys()
Out[26]: 
[u'GroundPixelQualityFlags',
 u'ImageMidpoint_TAI93',
 u'InstrumentQualityFlags',
 u'Latitude',
 u'LatitudeCorner',
 u'Longitude',
 u'LongitudeCorner',
 u'RelativeAzimuthAngle',
 u'SolarAzimuthAngle',
 u'SolarZenithAngle',
 u'SpacecraftAltitude',
 u'SpacecraftLatitude',
 u'SpacecraftLongitude',
 u'SpacecraftSolarZenith',
 u'UTC_CCSDA_A',
 u'ViewingAzimuthAngle',
 u'ViewingZenithAngle']

In [15]: f['ScienceData'].keys()
Out[15]: 
[u'AerosolIndex',
 u'CloudFraction',
 u'CloudPressure',
 u'CloudRefletivity',
 u'ColumnAmountO3isf',
 u'ColumnAmountO3pair',
 u'ColumnAmountSO2_ABV',
 u'ColumnAmountSO2_PBL',
 u'ColumnAmountSO2_STL',
 u'ColumnAmountSO2_TRL',
 u'ColumnAmountSO2_TRM',
 u'ColumnAmountSO2_TRU',
 u'GroundRefletivity',
 u'PixelQualityFlags',
 u'RadiativeCloudFraction',
 u'ScenePressure',
 u'SceneRefletivity',
 u'SlantColumnAmountSO2',
 u'TerrainPressure']
```
