### ISSUE TITLE
Question/Request: Consistent scale for all scenes

### ISSUE THREAD

**Issue by AlysonR** [pytroll/satpy#857]
Hi I was wondering when SatPy creates a composite or channel image based on the MODIS L1 radiances if the scales for the colors are the same across any number of images? Say for instance I create an image of channel 29 of MODIS and then want to compare against the same channel for a different day, would the colors created by SatPy coordinate to the same values across the two images?

**Comment by djhoese** [comment]
This has been something we've been discussing a lot. The main point of what you are talking about is "enhancement" in Satpy. For almost all images that are configured in Satpy (all the builtin RGBs and bands should be in one way or another) the images should be consistent from scene to scene. For reflectance (visible) channels from the L1 data this is also true; the data is clipped to a 0% to 100% reflectance range, followed by a gamma 1.5 operation. This was a compromise between @mraspaud and me to produce the "best" image possible.

The only major band type that does not fit this expectation is with the standard_name "toa_brightness_temperature", so any IR channel. Right now this dynamically finds the min and max of the data and stretches the data linearly between them. However, this means that for each scene these min/maxes are different. The main thing holding us up on making this consistent between scenes seems to be whether clouds should be white (meaning flip the data range) or black (keep the data as it is). The other point is that the range used for BT bands changes from channel to channel and from instrument to instrument so it is hard to have a good default for all BT bands.

Regardless, it is possible to customize how these are scaled by specifying your own enhancement configuration. Unfortunately this isn't extremely well documented. The short answer is to create a `enhancements/generic.yaml` in your current working directory that looks something like this:

```
enhancements:
  default:
    operations:
    - name: stretch
      method: &stretchfun !!python/name:satpy.enhancements.stretch
      kwargs: {stretch: linear}
  custom_bt:
    standard_name: toa_brightness_temperature
    operations:
    - name: linear_stretch
      method: !!python/name:satpy.enhancements.stretch
      kwargs: {stretch: 'crude', min_stretch: 240.0, max_stretch: 320.0}
```

You can see the builtin ones from Satpy here:
https://github.com/pytroll/satpy/blob/master/satpy/etc/enhancements/generic.yaml

Let me know if you have any additional questions or if you have any good suggestions for a good BT default enhancement.
