### ISSUE TITLE
Himawari-8 B13 image is negative?

### ISSUE THREAD

**Issue by weiluenju** [pytroll/satpy#865]
**Describe the bug**
I try to use the satpy to get the himawari-8 B13 band image, but the image is negative.
Is it a bug or I miss something?
Thank you.

**To Reproduce**
from satpy.scene import Scene
from satpy.resample import get_area_def
from datetime import datetime
from glob import glob
from pyresample.utils import get_area_def

FILES = glob("./data/*DAT")
scn = Scene(sensor='ahi',filenames=FILES,reader='ahi_hsd')
print(scn.available_dataset_names())
band = "B13"
scn.load([band])
scn.save_datasets(writer='simple_image')

**Expected behavior**
![2](https://user-images.githubusercontent.com/10330207/62591901-bdb05080-b903-11e9-9061-5a3d26dbd902.png)

**Actual results**
![1](https://user-images.githubusercontent.com/10330207/62591894-b9843300-b903-11e9-97a4-3fea1f05035e.png)

**Comment by simonrp84** [comment]
This is due to two different sets of people who like two different composites :) 
The default is cold = black and warm = white, but many (like you) prefer it the other way around.

@djhoese has previously suggested the following solution to create an 'inverse' Image for SEVIRI. You can use the same idea to create one for Himawari.

```
Create a etc/enhancements/seviri.yaml with the following contents:
enhancements:
 ch9_inverse:
    name: IR_108
    operations:
    - name: inverse
      method: *inversefun
      args:
      - [true, true, true]
    - name: stretch
      method: *stretchfun
      kwargs: {stretch: linear}
    - name: gamma
      method: *gammafun
      kwargs: {gamma: 1.6}
And point to this etc directory as suggested earlier with os.environ['PPP_CONFIG_DIR'] = '/path/to/your/etc'
```

Then you can use `ch9_inverse` (or whatever you choose to call it for Himawari) instead of `B13` to generate your image.
