### ISSUE TITLE
add resampling algorithms to composites in .yaml files

### ISSUE THREAD

**Issue by peters77** [pytroll/satpy#900]
## Feature Request

add additional entry for resampling algorithms in the .yaml file of composites

**Is your feature request related to a problem? Please describe.**
Use different reampling algorithms for combined composites or default composites to recommended resampling algorithms. Speed up for example static images resampling with nearest, IR channel with bilinear resampling for smoother and more quick computation in a combined composite composer. 

**Describe the solution you'd like**

```
static_day:
    compositor: !!python/name:satpy.composites.StaticImageCompositor
    standard_name: static_day
    filename: /pics/world.200407.3x21600x10800.png
    area: EPSG_4326
    resampling: nearest
```

**Describe any changes to existing user workflow**
Composite reampling algorithm should overwrite choosen algorithm in the script:

```
....
composite = 'clouds_with_background_day'
global_scene.load([composite])
new_scene = global_scene.resample(area, resampler='bilinear', nprocs=4, cache_dir='/tmp')
....
```
